name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    permissions:
      contents: write      
      id-token: write
      pages: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: |
            __FILES_GO_HERE__
          latexmk_use_xelatex: true
          continue_on_error: true
          working_directory: '__PUBLICATION_CONFIGURATION__'
          extra_fonts: |
            ./fonts/*.ttf
      - name: Upload PDF file to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: '__PUBLICATION_CONFIGURATION__'
          publish_branch: gh-pages
          destination_dir: '__PUBLICATION_CONFIGURATION__'
          keep_files: true
          exclude_assets: '**.xdv,**.log,**.fls,**.fdb_latexmk,**.aux,**.tex,fonts/**,.github/**,.github/workflows/**,openreader.cls'
      - name: Create and index for the page
        uses: openreadersbibles/create-indices-action@production
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: '.'
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
